### ISSUE TITLE
Account for lat/long updates in WQP via site auto validation

### ISSUE THREAD

**Issue by jakevl** [utah-dwq/irTools#64]
Currently, sites in the master site file for which a change is detected in lat or long are sent to auto validation. However, the lat/long are not updated to reflect that change before conducting auto validation. These should be updated/replaced. However, an override is needed for those sites for which the lat/long was manually modified. This is OK for this cycle. Needed for next cycle.

Also encountered 'duplicated' sites occurring due to ML name changes. Need a way to incorporate updates to sites to master site file through time w/o re-doing manual reviews.

**Comment by edhinman** [comment]
For the 2024 IR, EDH elected to create a new validateSites function that is not dependent upon a master site file from a previous cycle. Master site file was prone to issues relating to metadata changes in WQP and discouraged continual review of sites considered within each cycle. Instead, DWQ maintains a list of manual changes/rejections for sites based on MLID. These are applied/added to each cycle as new sites are considered. A downside to this approach is that some sites may be continually re-reviewed for flagged reasons (e.g. river sites in a lake AU), but could be added to the manual changes file.
